Show server logs on failure

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -92,6 +92,10 @@ jobs:
         run: |
           EXPECTED_REGEX="$EXPECTED_REGEX" docker compose run --rm --no-deps bot_${VERSION//./_}
 
+      - name: Show logs on failure
+        if: failure()
+        run: cat servers/${VERSION}/logs/latest.log || echo "Log not found"
+
       - name: Show bot logs on failure
         if: failure()
         run: docker compose logs --no-color bot_${VERSION//./_} || true
